// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ6QQr2u8kLVp4z4uw3QA_u50umqKN-YA',
    appId: '1:23940631567:web:2d06439471b45c7ea9677a',
    messagingSenderId: '23940631567',
    projectId: 'classwork-88616',
    authDomain: 'classwork-88616.firebaseapp.com',
    storageBucket: 'classwork-88616.firebasestorage.app',
    measurementId: 'G-NZJYR0RB6H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf4uM0GUd2Uaa6g2BRoYp5YvXIq4f-dXQ',
    appId: '1:23940631567:android:2435a474e8cb285aa9677a',
    messagingSenderId: '23940631567',
    projectId: 'classwork-88616',
    storageBucket: 'classwork-88616.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVtMxuotGnlCrceEp4NrxWrXettMxwoWI',
    appId: '1:23940631567:ios:61674278832c3f6aa9677a',
    messagingSenderId: '23940631567',
    projectId: 'classwork-88616',
    storageBucket: 'classwork-88616.firebasestorage.app',
    iosBundleId: 'com.example.classwork',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVtMxuotGnlCrceEp4NrxWrXettMxwoWI',
    appId: '1:23940631567:ios:61674278832c3f6aa9677a',
    messagingSenderId: '23940631567',
    projectId: 'classwork-88616',
    storageBucket: 'classwork-88616.firebasestorage.app',
    iosBundleId: 'com.example.classwork',
  );
}
